# Generated by Django 4.0 on 2023-02-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnbApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='listings',
            field=models.ManyToManyField(related_name='locations', to='bnbApp.Listing'),
        ),
    ]
