# Generated by Django 4.0 on 2023-02-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnbApp', '0002_location_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
