# Generated by Django 4.0 on 2023-02-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnbApp', '0004_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
    ]
