# Generated by Django 4.1.6 on 2023-02-20 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bnbApp', '0006_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
