# Generated by Django 4.1.6 on 2023-02-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnbApp', '0009_alter_review_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
